name: Build the container image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:

  build:
    name: Build the container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2.3.3
      - name: Log in to the GitHub registry
        run: docker login --password "${{ github.token }}" --username "${{ github.actor }}" docker.pkg.github.com
      - name: Build the container image
        run: docker image build --file Dockerfile --tag packer .
      - name: Tag and push the latest image
        if: github.event_name == 'push' || github.event_name == 'release'
        run: |
          docker image tag packer docker.pkg.github.com/${{ github.repository }}/packer:latest
          docker image push docker.pkg.github.com/${{ github.repository }}/packer:latest
      - name: Tag and push the release image
        if: github.event_name == 'release'
        run: |
          docker image tag packer docker.pkg.github.com/${{ github.repository }}/packer:${{ github.event.release.tag_name }}
          docker image push docker.pkg.github.com/${{ github.repository }}/packer:${{ github.event.release.tag_name }}
